import { CampaignNotFoundError, CompassRevisionConflictError, InvalidCampaignInputError, RulesetVersionNotFoundError } from "@/modules/campaigns";
import { BlueprintAlreadyMaterializedError, BlueprintIdempotencyConflictError, BlueprintNotFoundError, BlueprintReviewLockedError, BlueprintRevisionConflictError, InvalidBlueprintInputError } from "@/modules/blueprints";
import { UnauthenticatedError } from "@/modules/identity";
import { InvalidLocationInputError, InvalidLocationParentError, LocationNotFoundError, LocationRevisionConflictError } from "@/modules/locations";
import { ArcNotFoundError, ArcRevisionConflictError, InvalidArcInputError } from "@/modules/arcs";
import { InvalidQuestArcError, InvalidQuestInputError, InvalidQuestParentError, QuestNotFoundError, QuestRevisionConflictError } from "@/modules/quests";
import { InvalidNpcInputError, NpcNotFoundError, NpcRevisionConflictError } from "@/modules/npcs";
import { InvalidPlayerCharacterInputError, PlayerCharacterNotFoundError, PlayerCharacterRevisionConflictError } from "@/modules/player-characters";
import { InvalidPartyInputError, InvalidPartyMemberError, PartyNotFoundError, PartyRevisionConflictError } from "@/modules/parties";
import { FactionNotFoundError, FactionRevisionConflictError, InvalidFactionInputError, InvalidFactionMembershipError } from "@/modules/factions";
import { InvalidTravelRouteInputError, TravelRouteNotFoundError, TravelRouteRevisionConflictError } from "@/modules/travel-routes";
import { InvalidItemInputError, ItemNotFoundError, ItemRevisionConflictError } from "@/modules/items";
import { InvalidRelationshipInputError, RelationshipNotFoundError, RelationshipRevisionConflictError } from "@/modules/relationships";
import { InvalidTimelineEventInputError, TimelineEventNotFoundError, TimelineEventRevisionConflictError } from "@/modules/timeline";
import { InvalidSessionInputError, SceneNotFoundError, SessionCopyIdempotencyConflictError, SessionNotFoundError, SessionRevisionConflictError } from "@/modules/sessions";
import { EncounterCreatureNotFoundError, EncounterNotFoundError, EncounterPlacementNotFoundError, EncounterRevisionConflictError, InvalidEncounterInputError, InvalidEncounterRunInputError, UnsupportedEncounterVersionError } from "@/modules/encounters";
import { InvalidRewardInputError, RewardComponentNotFoundError, RewardNotFoundError, RewardRevisionConflictError } from "@/modules/rewards";

export type ActionState = { message: string; conflict?: boolean };
export function actionError(error: unknown): ActionState {
  if (error instanceof RewardRevisionConflictError) return { message: "This reward changed since you opened it. Reload before saving again.", conflict: true };
  if (error instanceof RewardNotFoundError || error instanceof RewardComponentNotFoundError)
    return { message: "Reward or component not found or unavailable." };
  if (error instanceof InvalidRewardInputError) return { message: "Enter a reward title and check its components." };
  if (error instanceof InvalidEncounterRunInputError) return { message: "Choose an available encounter or enter an improvised title, then describe what happened." };
  if (error instanceof EncounterRevisionConflictError) return { message: "This encounter changed since you opened it. Reload before saving again.", conflict: true };
  if (error instanceof EncounterCreatureNotFoundError || error instanceof EncounterNotFoundError)
    return { message: "Encounter or creature not found or unavailable." };
  if (error instanceof UnsupportedEncounterVersionError) return { message: "Encounter building is unavailable for this campaign's ruleset version." };
  if (error instanceof InvalidEncounterInputError) return { message: "Check the title, party level, party size, and creature values." };
  if (error instanceof SessionCopyIdempotencyConflictError) return { message: "This copy request belongs to another operation. Reload before trying again.", conflict: true };
  if (error instanceof SceneNotFoundError) return { message: "Scene not found or unavailable." };
  if (error instanceof EncounterPlacementNotFoundError) return { message: "Encounter placement not found. Reload the session." };
  if (error instanceof SessionRevisionConflictError) return { message: "This session changed since you opened it. Reload before saving again.", conflict: true };
  if (error instanceof SessionNotFoundError) return { message: "Session not found or unavailable." };
  if (error instanceof InvalidSessionInputError) return { message: "Check the session details and choose an available encounter or scene in this campaign." };
  if (error instanceof TimelineEventRevisionConflictError) return { message: "This event changed since you opened it. Reload before saving again.", conflict: true };
  if (error instanceof TimelineEventNotFoundError) return { message: "Timeline event not found or unavailable." };
  if (error instanceof InvalidTimelineEventInputError) return { message: "Enter an event title, a valid date, and available campaign entities." };
  if (error instanceof RelationshipRevisionConflictError) return { message: "This relationship changed since you opened it. Reload before saving again.", conflict: true };
  if (error instanceof RelationshipNotFoundError) return { message: "Relationship not found or unavailable." };
  if (error instanceof InvalidRelationshipInputError) return { message: "Choose two available campaign entities and enter a relationship type." };
  if (error instanceof ItemRevisionConflictError) return { message: "This item changed since you opened it. Reload before saving again.", conflict: true };
  if (error instanceof ItemNotFoundError) return { message: "Item not found or unavailable." };
  if (error instanceof InvalidItemInputError) return { message: "Enter an item name and choose an available holder or location in this campaign." };
  if (error instanceof TravelRouteRevisionConflictError) return { message: "This route changed since you opened it. Reload before saving again.", conflict: true };
  if (error instanceof TravelRouteNotFoundError) return { message: "Route not found or unavailable." };
  if (error instanceof InvalidTravelRouteInputError) return { message: "Enter a route name and choose two available locations in this campaign." };
  if (error instanceof FactionRevisionConflictError) return { message: "This faction changed since you opened it. Reload before saving again.", conflict: true };
  if (error instanceof FactionNotFoundError) return { message: "Faction not found or unavailable." };
  if (error instanceof InvalidFactionMembershipError) return { message: "Choose an available character in this campaign and check the membership details." };
  if (error instanceof InvalidFactionInputError) return { message: "Enter a faction name and check the details. If this continues, reload the page." };
  if (error instanceof PlayerCharacterRevisionConflictError) return { message: "This character changed since you opened it. Reload before saving again.", conflict: true };
  if (error instanceof PlayerCharacterNotFoundError) return { message: "Character not found or unavailable." };
  if (error instanceof InvalidPlayerCharacterInputError) return { message: "Enter a character name and check the details. If this continues, reload the page." };
  if (error instanceof PartyRevisionConflictError) return { message: "This party changed since you opened it. Reload before saving again.", conflict: true };
  if (error instanceof PartyNotFoundError) return { message: "Party not found or unavailable." };
  if (error instanceof InvalidPartyMemberError) return { message: "One of the selected characters is unavailable in this campaign." };
  if (error instanceof InvalidPartyInputError) return { message: "Enter a party name and check its description. If this continues, reload the page." };
  if (error instanceof NpcRevisionConflictError) return { message: "This NPC changed since you opened it. Reload before saving again.", conflict: true };
  if (error instanceof NpcNotFoundError) return { message: "NPC not found or unavailable." };
  if (error instanceof InvalidNpcInputError) return { message: "Enter an NPC name and check its details. If this continues, reload the page." };
  if (error instanceof QuestRevisionConflictError) return { message: "This quest changed since you opened it. Reload before saving again.", conflict: true };
  if (error instanceof QuestNotFoundError) return { message: "Quest not found or unavailable." };
  if (error instanceof InvalidQuestParentError) return { message: "That parent quest is unavailable or would create a cycle." };
  if (error instanceof InvalidQuestArcError) return { message: "One of the selected arcs is unavailable." };
  if (error instanceof InvalidQuestInputError) return { message: "Check the quest name, description, and status. If this continues, reload the page." };
  if (error instanceof ArcRevisionConflictError) return { message: "This arc changed since you opened it. Reload before saving again.", conflict: true };
  if (error instanceof ArcNotFoundError) return { message: "Arc not found or unavailable." };
  if (error instanceof InvalidArcInputError) return { message: "Enter an arc name and check its description. If this continues, reload the page." };
  if (error instanceof BlueprintRevisionConflictError) return { message: "This draft changed since you opened it. Reload before saving again.", conflict: true };
  if (error instanceof BlueprintNotFoundError) return { message: "Draft not found or unavailable." };
  if (error instanceof BlueprintReviewLockedError) return { message: "Location proposals are now edited in Review. Reload this draft before saving again.", conflict: true };
  if (error instanceof BlueprintAlreadyMaterializedError) return { message: "This draft has already created a campaign. Reload to open it.", conflict: true };
  if (error instanceof BlueprintIdempotencyConflictError) return { message: "This request key belongs to a different or unfinished operation. Reload before trying again.", conflict: true };
  if (error instanceof InvalidBlueprintInputError) return { message: "Enter a title and premise, with at most 20 proposed locations." };
  if (error instanceof CompassRevisionConflictError) return { message: "This compass changed since you opened it. Reload before saving again.", conflict: true };
  if (error instanceof LocationRevisionConflictError) return { message: "This location changed since you opened it. Reload before saving again.", conflict: true };
  if (error instanceof UnauthenticatedError) return { message: "Please sign in again before continuing." };
  if (error instanceof CampaignNotFoundError) return { message: "Campaign not found or unavailable." };
  if (error instanceof LocationNotFoundError) return { message: "Location not found or unavailable." };
  if (error instanceof RulesetVersionNotFoundError) return { message: "Campaign creation is temporarily unavailable. Please try again later." };
  if (error instanceof InvalidCampaignInputError) return { message: error.field === "currentPremise" ? "Enter a current premise and reload if this continues." : "Enter a name and original premise." };
  if (error instanceof InvalidLocationInputError) return { message: "Check the location fields. A name is required. If this continues, reload the page." };
  if (error instanceof InvalidLocationParentError) return { message: "That parent location is unavailable." };
  return { message: "Unable to complete this request. Please try again later." };
}
